### ISSUE TITLE
Localization of Digits

### ISSUE THREAD

**Issue by arashbm** [svenfuchs/i18n#183] opened 2012-12-22 18:28 UTC
Some languages use other digits than [Western Arabic](http://en.wikipedia.org/wiki/Arabic_numerals) (that is: 01234...). Some examples are [Eastern Arabic](http://en.wikipedia.org/wiki/Eastern_Arabic_numerals) (٠١٢٣٤٥٦٧٨٩: U+06F0..U+06F9) and Perso-Arabic (۰۱۲۳۴۵۶۷۸۹: U+0660..U+0669).

Is it within the scope of this gem to provide tools to localize digits of numbers? Can I provide pull request to extend `localize` or any new function to provide this facility?

**Comment by radar** [comment] 2016-11-03 06:04
This is a duplicate of #135. Let's keep the discussion there.

**Closed** 2016-11-03 20:05 UTC
