### ISSUE TITLE
http://ruby-i18n.org/wiki

### ISSUE THREAD

**Issue by mindware** [svenfuchs/i18n#323] opened 2015-09-11 15:22 UTC
This site appears to be unresponsive. If there is content there, such as examples of usage, perhaps they should be moved to the github wiki?

**Comment by arthurnn** [comment] 2015-09-13 16:25
Yes, we should move to GitHub wiki.
Anyone has access to the old content?

**Comment by mindware** [comment] 2015-09-14 13:19
Hi @arthurnn. If no one does, as a last resourt we could probably use the Internet Archive's:
https://web.archive.org/web/20140426174216/http://ruby-i18n.org/wiki

**Comment by ptarjan** [comment] 2016-04-27 02:57
+1

**Comment by radar** [comment] 2016-11-02 06:35
Please refer to this project's wiki for the time being https://github.com/svenfuchs/i18n/wiki.

@svenfuchs: when you get a moment, could you please update the description of the repo to point to the wiki also?

**Comment by dmitry** [comment] 2016-11-02 08:54
Duplicate of https://github.com/svenfuchs/i18n/issues/276

**Comment by sandstrom** [comment] 2016-12-04 14:41
friendly ping @svenfuchs

**Comment by lulalala** [comment] 2017-11-09 08:05
friendly ping @svenfuchs again, could you please update the description of the repo to point to the wiki?

**Closed** 2018-10-15 11:53 UTC
