### ISSUE TITLE
Plurization and Gettext modules don't play together

### ISSUE THREAD

**Issue by nikosd** [svenfuchs/i18n#113] opened 2011-11-04 07:38 UTC
Hi there, 

I believe there is a race condition between these two (I18n::Plurization and I18n:Gettext) that is caused due to unfinished todo on https://github.com/svenfuchs/i18n/blob/master/lib/i18n/gettext.rb#L13. 

The following example rails initializer :

``` ruby
require "i18n/backend/pluralization"
require "i18n/backend/gettext"

I18n::Backend::Simple.send(:include, I18n::Backend::Pluralization)
I18n::Backend::Simple.send(:include, I18n::Backend::Gettext)

I18n.load_path += Dir[Rails.root.join('config', 'locales', '**', '*.{rb,yml,ro}')]
```

alongside the [plurals.rb](https://github.com/svenfuchs/i18n/blob/master/test/test_data/locales/plurals.rb) file inside config/locales and the following example pl (Polish) translation that uses two plural forms instead of one :

```
#
msgid ""
msgstr ""
"Project-Id-Version: yum\n"
"Report-Msgid-Bugs-To: \n"
"PO-Revision-Date: 2009-07-31 16:36+0100\n"
"Last-Translator: Someone <someone@example.com>\n"
"Language-Team: Polish <someone@example.com>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"

msgid "1 gettext result"
msgid_plural "%{count} gettext results"
msgstr[0] "Polish 1 gettext result (0)"
msgstr[1] "Polish %{count} gettext results (1)"
msgstr[2] "Polish %{count} gettext results (2)"
```

cause the following exception to be raised on boot time :

```

/Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/i18n-0.6.0/lib/i18n/backend/gettext.rb:62:in `normalize_pluralization': invalid number of plurals: 3, keys: [:one, :other] (RuntimeError)
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/i18n-0.6.0/lib/i18n/backend/gettext.rb:43:in `normalize'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/i18n-0.6.0/lib/i18n/backend/base.rb:165:in `inject'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/i18n-0.6.0/lib/i18n/backend/gettext.rb:41:in `each'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/i18n-0.6.0/lib/i18n/backend/gettext.rb:41:in `inject'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/i18n-0.6.0/lib/i18n/backend/gettext.rb:41:in `normalize'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/i18n-0.6.0/lib/i18n/backend/gettext.rb:32:in `load_po'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/i18n-0.6.0/lib/i18n/backend/base.rb:157:in `send'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/i18n-0.6.0/lib/i18n/backend/base.rb:157:in `load_file'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/i18n-0.6.0/lib/i18n/backend/base.rb:15:in `load_translations'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/i18n-0.6.0/lib/i18n/backend/base.rb:15:in `each'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/i18n-0.6.0/lib/i18n/backend/base.rb:15:in `load_translations'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/i18n-0.6.0/lib/i18n/backend/simple.rb:57:in `init_translations'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/i18n-0.6.0/lib/i18n/backend/simple.rb:71:in `lookup'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/i18n-0.6.0/lib/i18n/backend/base.rb:26:in `translate'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/i18n-0.6.0/lib/i18n.rb:156:in `t'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/i18n-0.6.0/lib/i18n.rb:152:in `catch'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/i18n-0.6.0/lib/i18n.rb:152:in `t'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/activerecord-3.1.1/lib/active_record/railtie.rb:102
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/activesupport-3.1.1/lib/active_support/lazy_load_hooks.rb:34:in `call'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/activesupport-3.1.1/lib/active_support/lazy_load_hooks.rb:34:in `execute_hook'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/activesupport-3.1.1/lib/active_support/lazy_load_hooks.rb:43:in `run_load_hooks'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/activesupport-3.1.1/lib/active_support/lazy_load_hooks.rb:42:in `each'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/activesupport-3.1.1/lib/active_support/lazy_load_hooks.rb:42:in `run_load_hooks'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/railties-3.1.1/lib/rails/application/finisher.rb:56
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/railties-3.1.1/lib/rails/initializable.rb:30:in `instance_exec'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/railties-3.1.1/lib/rails/initializable.rb:30:in `run'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/railties-3.1.1/lib/rails/initializable.rb:55:in `run_initializers'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/railties-3.1.1/lib/rails/initializable.rb:54:in `each'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/railties-3.1.1/lib/rails/initializable.rb:54:in `run_initializers'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/railties-3.1.1/lib/rails/application.rb:96:in `initialize!'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/railties-3.1.1/lib/rails/railtie/configurable.rb:30:in `send'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/railties-3.1.1/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /Users/nikosd/Work/pamediakopes/tf18n/config/environment.rb:5
    from /Users/nikosd/Work/pamediakopes/tf18n/config.ru:4:in `require'
    from /Users/nikosd/Work/pamediakopes/tf18n/config.ru:4
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/rack-1.3.5/lib/rack/builder.rb:51:in `instance_eval'
    from /Users/nikosd/.rvm/gems/ree-1.8.7-2011.03@tfi18n/gems/rack-1.3.5/lib/rack/builder.rb:51:in `initialize'
    from /Users/nikosd/Work/pamediakopes/tf18n/config.ru:1:in `new'
    from /Users/nikosd/Work/pamediakopes/tf18n/config.ru:1
Exiting

Process finished with exit code 1

```

An ugly workaround is the following :

``` ruby
require "i18n/backend/pluralization"
I18n::Backend::Simple.send(:include, I18n::Backend::Pluralization)
I18n.load_path += Dir[Rails.root.join('config', 'locales', '**', '*.{rb,yml}')]

require "i18n/gettext"
# Monkey patch I18n::Gettext so we can set externally the plural keys
module I18n
  module Gettext
    def self.plural_keys=(plural_keys)
      @@plural_keys = plural_keys
    end
  end
end

# Load and set the plural keys before loading the Gettext backend alongside the po files
locale_plural_keys = {}
I18n.available_locales.each do |l|
  locale_plural_keys[l] = I18n.t(:'i18n.plural.keys', :locale => l, :resolve => false)
end
I18n::Gettext.plural_keys = locale_plural_keys

# Now load the Gettext backend
require "i18n/backend/gettext"
I18n::Backend::Simple.send(:include, I18n::Backend::Gettext)

# And finally the po files
I18n.load_path += Dir[Rails.root.join('config', 'locales', '**', '*.{po}')]
```

Which basically tries to load the po files _after_ the plural keys are properly set for all languages.

Another take (better, but still a hack is the following) :

(initializer)

``` ruby
require "pluralized_gettext_backend"
I18n::Backend::Simple.send(:include, I18n::Backend::PluralizedGettext)
I18n.load_path += Dir[Rails.root.join('config', 'locales', '**', '*.{rb,yml,po}')]
```

(pluralized_gettext_backend)

``` ruby
require "i18n/backend/pluralization"
require "i18n/backend/gettext"

module I18n
  module Backend
    # Hacking I18n::Backend::Pluralization and I18n::Backend::Gettext to play well together.
    # This is an abstraction of the following initializer hack
    # (for example config/initializers/i18n.rb) :
    #
    #  require "i18n/backend/pluralization"
    #  I18n::Backend::Simple.send(:include, I18n::Backend::Pluralization)
    #
    #  I18n.load_path += Dir[Rails.root.join('config', 'locales', '**', '*.{rb,yml}')]
    #
    #  locale_plural_keys = {}
    #  I18n.available_locales.each do |l|
    #    locale_plural_keys[l] = I18n.t(:'i18n.plural.keys', :locale => l, :resolve => false)
    #  end
    #  I18n::Gettext.plural_keys = locale_plural_keys
    #
    #  require "i18n/backend/gettext"
    #  I18n::Backend::Simple.send(:include, I18n::Backend::Gettext)
    #
    #  I18n.load_path += Dir[Rails.root.join('config', 'locales', '**', '*.{po}')]
    #
    # For this to work you need the following :
    #
    #   * plurals.rb under config/locales
    #   * Something like the following on your initializer :
    #
    #  require "pluralized_gettext_backend"
    #  I18n::Backend::Simple.send(:include, I18n::Backend::PluralizedGettext)
    #  I18n.load_path += Dir[Rails.root.join('config', 'locales', '**', '*.{rb,yml,po}')]
    #
    #
    # You can find the `plurals.rb` under https://github.com/svenfuchs/i18n/blob/master/test/test_data/locales/plurals.rb
    # Kudos to http://stackoverflow.com/questions/6166064/i18n-pluralization/6166091#6166091 !
    #
    # Have fun!
    module PluralizedGettext
      include Pluralization
      include Gettext

      def init_translations
        # load the plurals
        rules = load_rb(Rails.root.join('config', 'locales', 'plurals.rb'))

        # set the plural_forms
        rules.each do |locale, rule|
          I18n::Gettext.plural_keys[locale] = rule[:i18n][:plural][:keys]
        end

        Rails.logger.debug(I18n::Gettext.plural_keys.inspect) if defined?(Rails)

        # go on with your life...
        super
      end
    end
  end

  module Gettext
    def self.plural_keys(*args)
      args.length == 0 ? @@plural_keys : @@plural_keys[args.first] || @@plural_keys[:en]
    end
  end
end
```

I tried to think of a way to move the `plural keys` to the Pluralization module but I couldn't think of a nice way to do it taking into account all the lazy loading / caching / general magic that takes place in the localizations loading. If you give me a direction I can happily send a well-tested and documented patch.

Cheers and kudos for the good job with the i18n (even though I would do prefer a pure Gettext solution :D)

**Comment by radar** [comment] 2016-11-03 06:04
I am unable to reproduce this issue currently. Please provide an app which reproduces this issue.

**Comment by sandstrom** [comment] 2016-12-04 14:22
@nikosd Thanks for reporting this! I'd suggest closing this issue since it's old and there isn't a clear way to reproduce. Feel free to open a new issue if its still a problem.

**Closed** 2016-12-04 21:31 UTC
Labels: no-repro
