### ISSUE TITLE
Calling I18n.locale early breaks setup of I18n with default_locale

### ISSUE THREAD

**Issue by vollnhals** [svenfuchs/i18n#279] opened 2014-08-25 17:37 UTC
Calling I18n.locale early will set the locale permanently to `:en`. Calling default_locale is ignored.
We have a rails app where using a gem broke localization because this gem calls I18n.locale before the standard rails configuration script config/application.rb was run, which sets the default_locale to `:de`.

Calling I18n.locale too early should not break the localization setup.

Also see the bug that we opened for the corresponding gem, https://github.com/bernat/best_in_place/issues/393

**Comment by radar** [comment] 2016-11-02 11:04
Closing as a duplicate of #275

**Closed by radar** 2016-11-02 11:04 UTC
