### ISSUE TITLE
0.5.0 escapes input even with :escape => false

### ISSUE THREAD

**Issue by nhocki** [svenfuchs/i18n#100] opened 2011-06-21 18:02 UTC
Rails depends on i18n 0.5, and it has a simple bug that has been fixed by @pyromaniac in the pull request #85 but a new version of the gem was never updated. 

I was using the git repo until it changed to 0.6 by default and now rails won't accept it.

If you see the line 32 of lib/i18n/backend/chain.rb (https://github.com/svenfuchs/i18n/blob/0.5.0/lib/i18n/backend/chain.rb#L32), is it possible fix this and release a 0.5.1 that rails will accept?

Thanks

**Comment by radar** [comment] 2016-11-03 05:55
Closing this as it looks like the 0.5.1 release fixed it.

If it's still an issue, let me know by providing steps to reproduce it and I'll re-open.

**Closed by radar** 2016-11-03 05:55 UTC
