### ISSUE TITLE
Custom exception handlers only handling missing translations

### ISSUE THREAD

**Issue by jacobat** [svenfuchs/i18n#235] opened 2013-12-16 12:15 UTC
The exception handler registered on I18n is only used for handling `MissingTranslation` errors. Every other kind of error is simply propagated up the call stack. Example:

```
module I18n
  module Backend
    class Error
      include Base

      def lookup(locale, key, scope = [], options = {})
        case key
        when /missing/
          nil
        when /count/
          { :one => "one" }
        end
      end
    end
  end
end

I18n.backend = I18n::Backend::Error.new
I18n.exception_handler = ->(*args) { p args }
I18n.t('missing.something') # Outputs args from handler as excepted
I18n.t('count.something', :count => 2) # Raises exception
```

According to the Rails guides (http://guides.rubyonrails.org/i18n.html#using-different-exception-handlers) it should be possible to catch `InvalidPluralizationData` and `MissingInterpolationArgument` among others.

**Comment by radar** [comment] 2016-11-03 01:54
I cannot reproduce this issue on the latest version of i18n. I am going to close this issue.

If you're able to reproduce it, then please show me a way to do it and then let's work together on fixing this.

**Closed by radar** 2016-11-03 01:54 UTC

**Comment by tinbka** [comment] 2017-04-12 14:20
Currently you can do it like this:
```ruby
I18n.config.missing_interpolation_argument_handler = -> missing_key, provided_hash, string { string }
```

The only problem is that you have to look up the code; [official docs](http://guides.rubyonrails.org/i18n.html#using-different-exception-handlers) do not say anything about this method as if `I18n.exception_handler` were responsible for all the exception handling in `I18n.translate` which isn't right.
